//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.07 at 05:53:32 PM CEST 
//


package it.univaq.ir.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.univaq.ir.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TweetCollection_QNAME = new QName("http://www.di.univaq.it/TwitterCollection", "tweetCollection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.univaq.ir.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TweetCollection }
     * 
     */
    public TweetCollection createTweetCollection() {
        return new TweetCollection();
    }

    /**
     * Create an instance of {@link Tweet }
     * 
     */
    public Tweet createTweet() {
        return new Tweet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TweetCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.di.univaq.it/TwitterCollection", name = "tweetCollection")
    public JAXBElement<TweetCollection> createTweetCollection(TweetCollection value) {
        return new JAXBElement<TweetCollection>(_TweetCollection_QNAME, TweetCollection.class, null, value);
    }

}
