//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.07 at 05:53:32 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.di.univaq.it/TwitterCollection", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.univaq.ir.model;
